
* Simulation documentation

** LEADER simulation setup

Go through general setup for simulate cohort (Distributions
and variables, hooks etc.)

Then no effects yet. Output of LEADER data gives effects.
Can we trust these - leads nicely into next points

** Minimal simulation setup

Details of simulation setup and effects. Explain first how
data looks with continued randomized treatment. Then with
abrupt stops. (Go through how hooks implemented)

randomized treatment to begin. And either randomized stops/
starts or what?. Random dropout.

2 treatments [lira(glutide) / placebo], 1 visit, 1 outcome, same baseline
2 treatments, few visits, 1 outcome, same baseline

Should introduce different baseline? Might be beyond scope.

*** Continued treatment

Go through naive estimate, N of outcomes / N total (should work)

Maybe good for reference to have rtmle estimate (should work)

*** Abrupt stops in treatment

Go through naive estimates (shouldn't work)

then into rtmle estimate (should work)

** Checking leader estimates?





* PROGRESS CHECKLIST
** TODO outcomes happen before first scheduled visit atm.
Minimal   || baseline --> visit --> outcome
Extending || baseline --> visit --> visit ... --> outcome
Extending || abrupt starts/stops of treatment.
Extending || leader?

ask thomas whether there needs to be to seperate treatments
or treatment plus placebo is allright. 


long_to_wide.R line 325
