
* Simulation documentation

This, doc is meant as explanation and follow along for the sim
work done to verify analyses with the register targeted maximum
likelihood estimation (rtmle) package, and checking for bias
in different simple cases - hopefully extending as far as simulating
LEADER data based on past results and verifying that a subsequent
analysis recreates similar estimates (self-consistency).


** LEADER simulation setup

Go through general setup for simulate cohort (Distributions
and variables, hooks etc.). Then argue for the distributions
choosen for different variables.

Then no effects yet (how does it look). Output of LEADER data
gives effects. Can we trust these - leads nicely into next points

** Minimal simulation setup

Details of simulation setup and effects. Explain first how
data looks with continued randomized treatment. Then with
abrupt stops. (Go through how hooks implemented)

randomized treatment to begin. And either randomized stops/
starts or what?. Random dropout.

2 treatments [lira(glutide) / placebo], 1 visit, 1 outcome, same baseline
2 treatments, few visits, 1 outcome, same baseline

Should introduce different baseline (treatment could/should be
based on baseline variables)? 

*** Continuous treatment

Minimal simulation setting. People stay on randomized treatment. No dropout
within the timeframe.

Go through naive estimate, N of outcomes / N total. Taking the difference
between risk estimates of the two groups.

Kaplan-Meier reproduces the naive estimates.

Maybe good for reference to have rtmle estimate - something weird happening
now they do at least not agree completely. Seems that the risk associated with
the placebo in rtmle instead mimics the risk of death for the entire cohort.

* TODO ask Thomas.

In general end result would be nice as boxplots of estimates over
many sims, as done previously to asses bias in general.


*** Introducing abrupt stops in treatment

Introduce post visit hook to provide stops in treatment, based on intermediate events /
bloodwork - Maybe introduce bmi as a variable as well? (If weight drops too far below mean
maybe makes sense to stop)
Furthermore introduce censoring (dropout_scale non-zero)

Go through naive estimate (shouldn't work, gives results biased by
different underlying effects, as well as censoring/treatment changes)

Statistical model(s) Kaplan-Meier (Aalen-Johansen) (should work)

then into rtmle estimate (should work)

*** Competing event(s)


*** Non-randomized treatment






* PROGRESS CHECKLIST

**** REMEMBER ****
Looking for true effect value will look something like creating a large
dataset with no confounding effects and estimating either with naive or
kaplan-meier.

Keep steps simple. Introduce one change in the simulations at a time.

Make more systematic way to look at differences between truth. Boxplot
structure etc.


Minimal   || baseline --> outcome (no effects)
* DONE 
CLOSED: [2026-10-01 to 10:54]

randomized treatment

right now not the smartest solution to the minimal sim. Randomized
treatment already encodes all the info for lira and placebo.

Could just keep the one variable, and then introduce different protocols.
Seemingly if both placebo/lira variables were used to set the protocols
lead to different estimates.
* TODO without visit for minimal. Not super important for now.

baseline (effect on treatment)
baseline --> outcome.
then baseline --> treatment --> outcome (effects of values on updated treatments)
Extending || Confounding effects (treatment affected by covariate(s) that
also affect the risk of outcome directly)
* TODO introduce confounding effects. Fits well with treatment update hook

Extending || Competing outcomes (censoring eg. or introduce both death
and diabetes, or cv.death and all.cause.mortality)
* TODO

Extending || LEADER (using actual data, give parameters to
LEADER sim and check that the input matches the output over many
different sims)
* TODO

Along the way will introduce effects as they start to make sense.



