
* Notes

** Input for simulate cohort
p contains,
- Maximum number of events for the sim.
- How baseline parameter values are distributed
- How events/visits are distributed.
- parameter values:
  (intercept, relating to expected values of parameters and the
  timeline of events)
  (scale, relating to likelihood of events)
  (effect, effects of different parameters on eachother,
  effects of different parameters/events on likelihood of events,
  as well as treatments on the parameters/events)

** What happens to simulated data for different values of scale_dropout
scale_dropout < 0 (No other events past baseline)
scale_dropout = 0 (In general goes to the maximum amount of events,
max_follow = 6, but dropouts still occur for most)
scale_dropout > 0 (Increasing rate of dropout events)

* TODO Randomized treatment Diabetes data generation (similar time-series to Kathrine data)
- Create setting p (distributions/schedule/parameters/effects) that
  will mimick time-series of LEADER study data, through simulate
  cohort. (MIGHT BE DONE)

* TODO Simulate Diabetes register type data
- create setting with appropriate variables/distributions/events etc
  making timeseries that mimicks register data.

* Other thing causal changes in treatment
