
* Notes

** Input for simulate cohort
p contains,
- Maximum number of events for the sim.
- How baseline parameter values are distributed
- How events/visits are distributed.
- parameter values:
  (intercept, relating to expected values of parameters and the
  timeline of events)
  (scale, relating to likelihood of events)
  (effect, effects of different parameters on eachother,
  effects of different parameters/events on likelihood of events,
  as well as treatments on the parameters/events)
Effects.
Variables --> Variables
Variables --> Events (intermediate/absorbing)
Intermediate --> Events
No
Events --> Variables? Why should measurements in general not change
as a result of an events?

** What happens to simulated data for different values of scale_dropout
scale_dropout < 0 (No other events past baseline)
scale_dropout = 0 (In general goes to the maximum amount of events,
max_follow = 6, but dropouts still occur for most)
scale_dropout > 0 (Increasing rate of dropout events)

* DONE Randomized treatment Diabetes data generation (similar time-series to Kathrine data)
CLOSED: [2026-06-04 to 13:30]
- Create setting p (distributions/schedule/parameters/effects) that
  will mimick time-series of LEADER study data, through simulate
  cohort. (EXAMPLE SETTING DONE). First try shared with Thomas.

* DONE Need to modify to handle variance different from one apparently.
CLOSED: [2026-06-10 on 10:10]

* DONE Visits do not seem to follow the schedule. Check it out.
CLOSED: [2026-06-18 to 09:38]

* TODO Smaller sims. Naive risk estimate --> RTMLE
Difference in effect between treatment and placebo. First for
all same baseline, with continued treatment. Then for abrupt stop
treatment. Look "Documentation.org"


* LEADER SIM Status
- go through output effects on outcomes, for those that make sense
- mean/variance values (i.e. distributions of the variables) cannot
  be gotten from here. Have to look at the actual data.

have to make input list effects for each scheduled time step (output
of rtmle gives effects at each time-step)
Insert hook in simulate cohort that updates the parameter used parameter
values for the sim, based on where in time it is w.r.t. the schedule
grid.

Ok so want hooks that can:
- group appropriate variables post baseline (done) - However
  maybe they need there own variables to categorize effects.
- update the linear coefficients given time step (from schedule)
- Stop lira with some probability post visit (probably save as
  stopped)






** Talk with Kathrine at some point
- Have rough outline from looking at the leader targets pipeline.
  Have made assumptions about distributions of differnet variables.

- I think the only measurement variables listed in the pipeline
  is a1c level/change, which i think works nicely in the simulation.
  Should the rest of the baseline biomarkers be updated as well?

- Then generally what effects between covariates/events are relevant.

- Is there a large difference in the likelihood between events

What do i need specifically?
- Mean/variance values that make sense.
- Scales of event probabilities (Maybe relative is enough)
- Changes in distributions?
- Update biomarkers?


* TODO Simulate Diabetes register type data
- create setting with appropriate variables/distributions/events etc
  making timeseries that mimicks register data.

** Overview
- First step is to recreate simulated timeseries of correct
  names/variables. Trying one register at a time (a lot of events
  may be NULL).
  Ok so thing is, if they are independently simulated how does
  one match ids from different registers. Does not really make
  sense to do it like that i suppose. Make together (entire
  history of person is followed) such that the progression of
  the registers is alligned - Then split registers (if made for
  test of get_DMreg()).
- What makes sense to make here. Should it be some population
  with some percentage chance of getting a diabetes entry.

** How does the typical history look?
Most likely they get diagnosis/lab first then prescription. No foot first
right? What about the others. Maybe look at 3740 for shape and overview
of the data.

Need data like: MFR, PDB, LPR, LMDB, LABKA, (SSR, DVDD)

** Other thing causal changes in treatment
