
* Notes

** Input for simulate cohort
p contains,
- Maximum number of events for the sim.
- How baseline parameter values are distributed
- How events/visits are distributed.
- parameter values:
  (intercept, relating to expected values of parameters and the
  timeline of events)
  (scale, relating to likelihood of events)
  (effect, effects of different parameters on eachother,
  effects of different parameters/events on likelihood of events,
  as well as treatments on the parameters/events)
Effects.
Variables --> Variables
Variables --> Events (intermediate/absorbing)
Intermediate --> Events
No
Events --> Variables? Why should measurements in general not change
as a result of an events?

** What happens to simulated data for different values of scale_dropout
scale_dropout < 0 (No other events past baseline)
scale_dropout = 0 (In general goes to the maximum amount of events,
max_follow = 6, but dropouts still occur for most)
scale_dropout > 0 (Increasing rate of dropout events)

* DONE Randomized treatment Diabetes data generation (similar time-series to Kathrine data)
CLOSED: [2026-06-04 to 13:30]
- Create setting p (distributions/schedule/parameters/effects) that
  will mimick time-series of LEADER study data, through simulate
  cohort. (EXAMPLE SETTING DONE). First try shared with Thomas.

* DONE Need to modify to handle variance different from one apparently.
CLOSED: [2026-06-10 on 10:10]

* TODO Visits do not seem to follow the schedule. Check it out.
Okay seems to me that the scheduling in some sense "fails" - at least
if the intention is to have visits every 6 months. However they are
instead spaced such that the visit happens exactly 6 months after the
previous event. Is this the intention? ASK thomas.

Also weird that visits "compete" with events...
Try fix? Remember to mark changes in functionality.

Should the biomarkers be updated at every type of event?

Have made baseline treatment (either lira or placebo) randomized.



** Talk with Kathrine at some point
- Have rough outline from looking at the leader targets pipeline.
  Have made assumptions about distributions of differnet variables.

- I think the only measurement variables listed in the pipeline
  is a1c level/change, which i think works nicely in the simulation.
  Should the rest of the baseline biomarkers be updated as well?

- Then generally what effects between covariates/events are relevant.

- Is there a large difference in the likelihood between events

What do i need specifically?
- Mean/variance values that make sense.
- Scales of event probabilities (Maybe relative is enough)
- Changes in distributions?
- Update biomarkers?


* TODO Simulate Diabetes register type data
- create setting with appropriate variables/distributions/events etc
  making timeseries that mimicks register data.

** Overview
- First step is to recreate simulated timeseries of correct
  names/variables. Trying one register at a time (a lot of events
  may be NULL).
  Ok so thing is, if they are independently simulated how does
  one match ids from different registers. Does not really make
  sense to do it like that i suppose. Make together (entire
  history of person is followed) such that the progression of
  the registers is alligned - Then split registers (if made for
  test of get_DMreg()).
- What makes sense to make here. Should it be some population
  with some percentage chance of getting a diabetes entry.

** How does the typical history look?
Most likely they get diagnosis/lab first then prescription. No foot first
right? What about the others. Maybe look at 3740 for shape and overview
of the data.

Need data like: MFR, PDB, LPR, LMDB, LABKA, (SSR, DVDD)



* Other thing causal changes in treatment
