### get_LEADER_setting.R --- 
#----------------------------------------------------------------------
## Author: 
## Created: jun  2 2026 (12:44) 
## Version: 
## Last-Updated: jun  4 2026 (14:42) 
##           By: SADS0006
##     Update #: 14
#----------------------------------------------------------------------
## 
### Commentary: 
## 
### Change Log:
#----------------------------------------------------------------------
## 
### Code:

get_LEADER_setting <- function(){

    #-----------------------Parameters-----------------------------

    # Maximum amount of followup events in the time-series
    max_follow <- 24

    # Baseline variables and their distributions
    baseline_variables <- list(
        # demographics
        sex = "binomial",
        age = "normal",
        diabetesduration = "binomial",
        
        # baseline biomarkers
        egfr = "normal",
        bmi = "normal",
        
        # baseline concomitant medication
        mineralcor = "binomial",
        bb = "binomial",
        rasi = "binomial",
        loop = "binomial",
        ccb = "binomial",
        thiazide = "binomial",
        sasid = "binomial",
        statin = "binomial",
        
        # baseline comorbidities
        hypertension = "binomial",
        diabetic.nephropathy = "binomial",
        stenosis = "binomial",
        disorders.of.rhythm.or.conduction = "binomial",
        left.ventricular.systolic.dysfunction = "binomial",
        gallstone.disease = "binomial",
        pancreatitis = "binomial",
        diabetic.foot.ulcer = "binomial",
        diabetic.neuropathy = "binomial",
        transient.ischaemic.attack = "binomial"
    )

    # List of events ending the time-series (death/dropout/censoring)
    absorbing_events <- list(
        cv.death = "Weibull",
        all.cause.mortality = "Weibull",
        dropout = "Weibull"
    )

    # List of other possible events between visits.
    intermediate_events <- list(
        # chronic events
        mi = "Weibull",
        stroke = "Weibull",
        uap = "Weibull",
        revasc = "Weibull",
        heart.failure = "Weibull",
        
        # periodic adverse events
        atrial.fibrillation = "Weibull",
        nausea.and.vomiting.symptoms = "Weibull",
        diarrhoea = "Weibull"
    )

    # What is measured at a visit
    visit_measurements <- list(
        hba1c_level = "normal",
        hba1c_change = "normal"
    )

    # What info is given at baseline
    baseline_visit <- list(
        start_GLP1RA = "binomial",
        start_SGLT2i = "binomial"
    )

    # What could happen based on the visit (Medication/treatment)
    visit_events <- list(
        # glucose-lowering medication states/actions
        metformin = "binomial",
        sulfonylurea = "binomial",
        insulin = "binomial",
        alfa_g_inhib = "binomial",
        thiazo = "binomial",
        insulin_one = "binomial",
        dpp4 = "binomial"
    )

    # Thomas says here 0,1,3,6,12 and so on. Should it be random?
    # Change later he says. Have made 6 month grid. Add 1,3 in post?
    visit_schedule <- list(
        mean =  6, sd = 0, skip = 0
    )


    
    #-----------------------Setting-List---------------------------

    # Generate initial parameter values list
    if (FALSE){
    ipv = initialize_parameter_values(
        baseline_variables = baseline_variables,
        absorbing_events = absorbing_events,
        baseline_visit = baseline_visit,
        intermediate_events = intermediate_events,
        visit_measurements = visit_measurements,
        visit_events = visit_events,
        visit_schedule = visit_schedule)
    dput(ipv)
    }
    
    list(intercept_sex = 0, intercept_age = 0, intercept_diabetesduration = 0, 
         intercept_egfr = 0, intercept_bmi = 0, intercept_mineralcor = 0, 
         intercept_bb = 0, intercept_rasi = 0, intercept_loop = 0, 
         intercept_ccb = 0, intercept_thiazide = 0, intercept_sasid = 0, 
         intercept_statin = 0, intercept_hypertension = 0, intercept_diabetic.nephropathy = 0, 
         intercept_stenosis = 0, intercept_disorders.of.rhythm.or.conduction = 0, 
         intercept_left.ventricular.systolic.dysfunction = 0, intercept_gallstone.disease = 0, 
         intercept_pancreatitis = 0, intercept_diabetic.foot.ulcer = 0, 
         intercept_diabetic.neuropathy = 0, intercept_transient.ischaemic.attack = 0, 
         intercept_start_GLP1RA = 0, intercept_start_SGLT2i = 0, intercept_hba1c_level = 0, 
         intercept_hba1c_change = 0, intercept_metformin = 0, intercept_sulfonylurea = 0, 
         intercept_insulin = 0, intercept_alfa_g_inhib = 0, intercept_thiazo = 0, 
         intercept_insulin_one = 0, intercept_dpp4 = 0, variance_age = 1, 
         variance_egfr = 1, variance_bmi = 1, variance_hba1c_level = 1, 
         variance_hba1c_change = 1, scale_cv.death = 0.01, scale_all.cause.mortality = 0.01, 
         scale_dropout = 0.01, scale_mi = 0.01, scale_stroke = 0.01, 
         scale_uap = 0.01, scale_revasc = 0.01, scale_heart.failure = 0.01, 
         scale_atrial.fibrillation = 0.01, scale_nausea.and.vomiting.symptoms = 0.01, 
         scale_diarrhoea = 0.01, effect_age_sex = 0, effect_diabetesduration_sex = 0, 
         effect_egfr_sex = 0, effect_bmi_sex = 0, effect_mineralcor_sex = 0, 
         effect_bb_sex = 0, effect_rasi_sex = 0, effect_loop_sex = 0, 
         effect_ccb_sex = 0, effect_thiazide_sex = 0, effect_sasid_sex = 0, 
         effect_statin_sex = 0, effect_hypertension_sex = 0, effect_diabetic.nephropathy_sex = 0, 
         effect_stenosis_sex = 0, effect_disorders.of.rhythm.or.conduction_sex = 0, 
         effect_left.ventricular.systolic.dysfunction_sex = 0, effect_gallstone.disease_sex = 0, 
         effect_pancreatitis_sex = 0, effect_diabetic.foot.ulcer_sex = 0, 
         effect_diabetic.neuropathy_sex = 0, effect_transient.ischaemic.attack_sex = 0, 
         effect_sex_age = 0, effect_diabetesduration_age = 0, effect_egfr_age = 0, 
         effect_bmi_age = 0, effect_mineralcor_age = 0, effect_bb_age = 0, 
         effect_rasi_age = 0, effect_loop_age = 0, effect_ccb_age = 0, 
         effect_thiazide_age = 0, effect_sasid_age = 0, effect_statin_age = 0, 
         effect_hypertension_age = 0, effect_diabetic.nephropathy_age = 0, 
         effect_stenosis_age = 0, effect_disorders.of.rhythm.or.conduction_age = 0, 
         effect_left.ventricular.systolic.dysfunction_age = 0, effect_gallstone.disease_age = 0, 
         effect_pancreatitis_age = 0, effect_diabetic.foot.ulcer_age = 0, 
         effect_diabetic.neuropathy_age = 0, effect_transient.ischaemic.attack_age = 0, 
         effect_sex_diabetesduration = 0, effect_age_diabetesduration = 0, 
         effect_egfr_diabetesduration = 0, effect_bmi_diabetesduration = 0, 
         effect_mineralcor_diabetesduration = 0, effect_bb_diabetesduration = 0, 
         effect_rasi_diabetesduration = 0, effect_loop_diabetesduration = 0, 
         effect_ccb_diabetesduration = 0, effect_thiazide_diabetesduration = 0, 
         effect_sasid_diabetesduration = 0, effect_statin_diabetesduration = 0, 
         effect_hypertension_diabetesduration = 0, effect_diabetic.nephropathy_diabetesduration = 0, 
         effect_stenosis_diabetesduration = 0, effect_disorders.of.rhythm.or.conduction_diabetesduration = 0, 
         effect_left.ventricular.systolic.dysfunction_diabetesduration = 0, 
         effect_gallstone.disease_diabetesduration = 0, effect_pancreatitis_diabetesduration = 0, 
         effect_diabetic.foot.ulcer_diabetesduration = 0, effect_diabetic.neuropathy_diabetesduration = 0, 
         effect_transient.ischaemic.attack_diabetesduration = 0, effect_sex_egfr = 0, 
         effect_age_egfr = 0, effect_diabetesduration_egfr = 0, effect_bmi_egfr = 0, 
         effect_mineralcor_egfr = 0, effect_bb_egfr = 0, effect_rasi_egfr = 0, 
         effect_loop_egfr = 0, effect_ccb_egfr = 0, effect_thiazide_egfr = 0, 
         effect_sasid_egfr = 0, effect_statin_egfr = 0, effect_hypertension_egfr = 0, 
         effect_diabetic.nephropathy_egfr = 0, effect_stenosis_egfr = 0, 
         effect_disorders.of.rhythm.or.conduction_egfr = 0, effect_left.ventricular.systolic.dysfunction_egfr = 0, 
         effect_gallstone.disease_egfr = 0, effect_pancreatitis_egfr = 0, 
         effect_diabetic.foot.ulcer_egfr = 0, effect_diabetic.neuropathy_egfr = 0, 
         effect_transient.ischaemic.attack_egfr = 0, effect_sex_bmi = 0, 
         effect_age_bmi = 0, effect_diabetesduration_bmi = 0, effect_egfr_bmi = 0, 
         effect_mineralcor_bmi = 0, effect_bb_bmi = 0, effect_rasi_bmi = 0, 
         effect_loop_bmi = 0, effect_ccb_bmi = 0, effect_thiazide_bmi = 0, 
         effect_sasid_bmi = 0, effect_statin_bmi = 0, effect_hypertension_bmi = 0, 
         effect_diabetic.nephropathy_bmi = 0, effect_stenosis_bmi = 0, 
         effect_disorders.of.rhythm.or.conduction_bmi = 0, effect_left.ventricular.systolic.dysfunction_bmi = 0, 
         effect_gallstone.disease_bmi = 0, effect_pancreatitis_bmi = 0, 
         effect_diabetic.foot.ulcer_bmi = 0, effect_diabetic.neuropathy_bmi = 0, 
         effect_transient.ischaemic.attack_bmi = 0, effect_sex_mineralcor = 0, 
         effect_age_mineralcor = 0, effect_diabetesduration_mineralcor = 0, 
         effect_egfr_mineralcor = 0, effect_bmi_mineralcor = 0, effect_bb_mineralcor = 0, 
         effect_rasi_mineralcor = 0, effect_loop_mineralcor = 0, effect_ccb_mineralcor = 0, 
         effect_thiazide_mineralcor = 0, effect_sasid_mineralcor = 0, 
         effect_statin_mineralcor = 0, effect_hypertension_mineralcor = 0, 
         effect_diabetic.nephropathy_mineralcor = 0, effect_stenosis_mineralcor = 0, 
         effect_disorders.of.rhythm.or.conduction_mineralcor = 0, 
         effect_left.ventricular.systolic.dysfunction_mineralcor = 0, 
         effect_gallstone.disease_mineralcor = 0, effect_pancreatitis_mineralcor = 0, 
         effect_diabetic.foot.ulcer_mineralcor = 0, effect_diabetic.neuropathy_mineralcor = 0, 
         effect_transient.ischaemic.attack_mineralcor = 0, effect_sex_bb = 0, 
         effect_age_bb = 0, effect_diabetesduration_bb = 0, effect_egfr_bb = 0, 
         effect_bmi_bb = 0, effect_mineralcor_bb = 0, effect_rasi_bb = 0, 
         effect_loop_bb = 0, effect_ccb_bb = 0, effect_thiazide_bb = 0, 
         effect_sasid_bb = 0, effect_statin_bb = 0, effect_hypertension_bb = 0, 
         effect_diabetic.nephropathy_bb = 0, effect_stenosis_bb = 0, 
         effect_disorders.of.rhythm.or.conduction_bb = 0, effect_left.ventricular.systolic.dysfunction_bb = 0, 
         effect_gallstone.disease_bb = 0, effect_pancreatitis_bb = 0, 
         effect_diabetic.foot.ulcer_bb = 0, effect_diabetic.neuropathy_bb = 0, 
         effect_transient.ischaemic.attack_bb = 0, effect_sex_rasi = 0, 
         effect_age_rasi = 0, effect_diabetesduration_rasi = 0, effect_egfr_rasi = 0, 
         effect_bmi_rasi = 0, effect_mineralcor_rasi = 0, effect_bb_rasi = 0, 
         effect_loop_rasi = 0, effect_ccb_rasi = 0, effect_thiazide_rasi = 0, 
         effect_sasid_rasi = 0, effect_statin_rasi = 0, effect_hypertension_rasi = 0, 
         effect_diabetic.nephropathy_rasi = 0, effect_stenosis_rasi = 0, 
         effect_disorders.of.rhythm.or.conduction_rasi = 0, effect_left.ventricular.systolic.dysfunction_rasi = 0, 
         effect_gallstone.disease_rasi = 0, effect_pancreatitis_rasi = 0, 
         effect_diabetic.foot.ulcer_rasi = 0, effect_diabetic.neuropathy_rasi = 0, 
         effect_transient.ischaemic.attack_rasi = 0, effect_sex_loop = 0, 
         effect_age_loop = 0, effect_diabetesduration_loop = 0, effect_egfr_loop = 0, 
         effect_bmi_loop = 0, effect_mineralcor_loop = 0, effect_bb_loop = 0, 
         effect_rasi_loop = 0, effect_ccb_loop = 0, effect_thiazide_loop = 0, 
         effect_sasid_loop = 0, effect_statin_loop = 0, effect_hypertension_loop = 0, 
         effect_diabetic.nephropathy_loop = 0, effect_stenosis_loop = 0, 
         effect_disorders.of.rhythm.or.conduction_loop = 0, effect_left.ventricular.systolic.dysfunction_loop = 0, 
         effect_gallstone.disease_loop = 0, effect_pancreatitis_loop = 0, 
         effect_diabetic.foot.ulcer_loop = 0, effect_diabetic.neuropathy_loop = 0, 
         effect_transient.ischaemic.attack_loop = 0, effect_sex_ccb = 0, 
         effect_age_ccb = 0, effect_diabetesduration_ccb = 0, effect_egfr_ccb = 0, 
         effect_bmi_ccb = 0, effect_mineralcor_ccb = 0, effect_bb_ccb = 0, 
         effect_rasi_ccb = 0, effect_loop_ccb = 0, effect_thiazide_ccb = 0, 
         effect_sasid_ccb = 0, effect_statin_ccb = 0, effect_hypertension_ccb = 0, 
         effect_diabetic.nephropathy_ccb = 0, effect_stenosis_ccb = 0, 
         effect_disorders.of.rhythm.or.conduction_ccb = 0, effect_left.ventricular.systolic.dysfunction_ccb = 0, 
         effect_gallstone.disease_ccb = 0, effect_pancreatitis_ccb = 0, 
         effect_diabetic.foot.ulcer_ccb = 0, effect_diabetic.neuropathy_ccb = 0, 
         effect_transient.ischaemic.attack_ccb = 0, effect_sex_thiazide = 0, 
         effect_age_thiazide = 0, effect_diabetesduration_thiazide = 0, 
         effect_egfr_thiazide = 0, effect_bmi_thiazide = 0, effect_mineralcor_thiazide = 0, 
         effect_bb_thiazide = 0, effect_rasi_thiazide = 0, effect_loop_thiazide = 0, 
         effect_ccb_thiazide = 0, effect_sasid_thiazide = 0, effect_statin_thiazide = 0, 
         effect_hypertension_thiazide = 0, effect_diabetic.nephropathy_thiazide = 0, 
         effect_stenosis_thiazide = 0, effect_disorders.of.rhythm.or.conduction_thiazide = 0, 
         effect_left.ventricular.systolic.dysfunction_thiazide = 0, 
         effect_gallstone.disease_thiazide = 0, effect_pancreatitis_thiazide = 0, 
         effect_diabetic.foot.ulcer_thiazide = 0, effect_diabetic.neuropathy_thiazide = 0, 
         effect_transient.ischaemic.attack_thiazide = 0, effect_sex_sasid = 0, 
         effect_age_sasid = 0, effect_diabetesduration_sasid = 0, 
         effect_egfr_sasid = 0, effect_bmi_sasid = 0, effect_mineralcor_sasid = 0, 
         effect_bb_sasid = 0, effect_rasi_sasid = 0, effect_loop_sasid = 0, 
         effect_ccb_sasid = 0, effect_thiazide_sasid = 0, effect_statin_sasid = 0, 
         effect_hypertension_sasid = 0, effect_diabetic.nephropathy_sasid = 0, 
         effect_stenosis_sasid = 0, effect_disorders.of.rhythm.or.conduction_sasid = 0, 
         effect_left.ventricular.systolic.dysfunction_sasid = 0, effect_gallstone.disease_sasid = 0, 
         effect_pancreatitis_sasid = 0, effect_diabetic.foot.ulcer_sasid = 0, 
         effect_diabetic.neuropathy_sasid = 0, effect_transient.ischaemic.attack_sasid = 0, 
         effect_sex_statin = 0, effect_age_statin = 0, effect_diabetesduration_statin = 0, 
         effect_egfr_statin = 0, effect_bmi_statin = 0, effect_mineralcor_statin = 0, 
         effect_bb_statin = 0, effect_rasi_statin = 0, effect_loop_statin = 0, 
         effect_ccb_statin = 0, effect_thiazide_statin = 0, effect_sasid_statin = 0, 
         effect_hypertension_statin = 0, effect_diabetic.nephropathy_statin = 0, 
         effect_stenosis_statin = 0, effect_disorders.of.rhythm.or.conduction_statin = 0, 
         effect_left.ventricular.systolic.dysfunction_statin = 0, 
         effect_gallstone.disease_statin = 0, effect_pancreatitis_statin = 0, 
         effect_diabetic.foot.ulcer_statin = 0, effect_diabetic.neuropathy_statin = 0, 
         effect_transient.ischaemic.attack_statin = 0, effect_sex_hypertension = 0, 
         effect_age_hypertension = 0, effect_diabetesduration_hypertension = 0, 
         effect_egfr_hypertension = 0, effect_bmi_hypertension = 0, 
         effect_mineralcor_hypertension = 0, effect_bb_hypertension = 0, 
         effect_rasi_hypertension = 0, effect_loop_hypertension = 0, 
         effect_ccb_hypertension = 0, effect_thiazide_hypertension = 0, 
         effect_sasid_hypertension = 0, effect_statin_hypertension = 0, 
         effect_diabetic.nephropathy_hypertension = 0, effect_stenosis_hypertension = 0, 
         effect_disorders.of.rhythm.or.conduction_hypertension = 0, 
         effect_left.ventricular.systolic.dysfunction_hypertension = 0, 
         effect_gallstone.disease_hypertension = 0, effect_pancreatitis_hypertension = 0, 
         effect_diabetic.foot.ulcer_hypertension = 0, effect_diabetic.neuropathy_hypertension = 0, 
         effect_transient.ischaemic.attack_hypertension = 0, effect_sex_diabetic.nephropathy = 0, 
         effect_age_diabetic.nephropathy = 0, effect_diabetesduration_diabetic.nephropathy = 0, 
         effect_egfr_diabetic.nephropathy = 0, effect_bmi_diabetic.nephropathy = 0, 
         effect_mineralcor_diabetic.nephropathy = 0, effect_bb_diabetic.nephropathy = 0, 
         effect_rasi_diabetic.nephropathy = 0, effect_loop_diabetic.nephropathy = 0, 
         effect_ccb_diabetic.nephropathy = 0, effect_thiazide_diabetic.nephropathy = 0, 
         effect_sasid_diabetic.nephropathy = 0, effect_statin_diabetic.nephropathy = 0, 
         effect_hypertension_diabetic.nephropathy = 0, effect_stenosis_diabetic.nephropathy = 0, 
         effect_disorders.of.rhythm.or.conduction_diabetic.nephropathy = 0, 
         effect_left.ventricular.systolic.dysfunction_diabetic.nephropathy = 0, 
         effect_gallstone.disease_diabetic.nephropathy = 0, effect_pancreatitis_diabetic.nephropathy = 0, 
         effect_diabetic.foot.ulcer_diabetic.nephropathy = 0, effect_diabetic.neuropathy_diabetic.nephropathy = 0, 
         effect_transient.ischaemic.attack_diabetic.nephropathy = 0, 
         effect_sex_stenosis = 0, effect_age_stenosis = 0, effect_diabetesduration_stenosis = 0, 
         effect_egfr_stenosis = 0, effect_bmi_stenosis = 0, effect_mineralcor_stenosis = 0, 
         effect_bb_stenosis = 0, effect_rasi_stenosis = 0, effect_loop_stenosis = 0, 
         effect_ccb_stenosis = 0, effect_thiazide_stenosis = 0, effect_sasid_stenosis = 0, 
         effect_statin_stenosis = 0, effect_hypertension_stenosis = 0, 
         effect_diabetic.nephropathy_stenosis = 0, effect_disorders.of.rhythm.or.conduction_stenosis = 0, 
         effect_left.ventricular.systolic.dysfunction_stenosis = 0, 
         effect_gallstone.disease_stenosis = 0, effect_pancreatitis_stenosis = 0, 
         effect_diabetic.foot.ulcer_stenosis = 0, effect_diabetic.neuropathy_stenosis = 0, 
         effect_transient.ischaemic.attack_stenosis = 0, effect_sex_disorders.of.rhythm.or.conduction = 0, 
         effect_age_disorders.of.rhythm.or.conduction = 0, effect_diabetesduration_disorders.of.rhythm.or.conduction = 0, 
         effect_egfr_disorders.of.rhythm.or.conduction = 0, effect_bmi_disorders.of.rhythm.or.conduction = 0, 
         effect_mineralcor_disorders.of.rhythm.or.conduction = 0, 
         effect_bb_disorders.of.rhythm.or.conduction = 0, effect_rasi_disorders.of.rhythm.or.conduction = 0, 
         effect_loop_disorders.of.rhythm.or.conduction = 0, effect_ccb_disorders.of.rhythm.or.conduction = 0, 
         effect_thiazide_disorders.of.rhythm.or.conduction = 0, effect_sasid_disorders.of.rhythm.or.conduction = 0, 
         effect_statin_disorders.of.rhythm.or.conduction = 0, effect_hypertension_disorders.of.rhythm.or.conduction = 0, 
         effect_diabetic.nephropathy_disorders.of.rhythm.or.conduction = 0, 
         effect_stenosis_disorders.of.rhythm.or.conduction = 0, effect_left.ventricular.systolic.dysfunction_disorders.of.rhythm.or.conduction = 0, 
         effect_gallstone.disease_disorders.of.rhythm.or.conduction = 0, 
         effect_pancreatitis_disorders.of.rhythm.or.conduction = 0, 
         effect_diabetic.foot.ulcer_disorders.of.rhythm.or.conduction = 0, 
         effect_diabetic.neuropathy_disorders.of.rhythm.or.conduction = 0, 
         effect_transient.ischaemic.attack_disorders.of.rhythm.or.conduction = 0, 
         effect_sex_left.ventricular.systolic.dysfunction = 0, effect_age_left.ventricular.systolic.dysfunction = 0, 
         effect_diabetesduration_left.ventricular.systolic.dysfunction = 0, 
         effect_egfr_left.ventricular.systolic.dysfunction = 0, effect_bmi_left.ventricular.systolic.dysfunction = 0, 
         effect_mineralcor_left.ventricular.systolic.dysfunction = 0, 
         effect_bb_left.ventricular.systolic.dysfunction = 0, effect_rasi_left.ventricular.systolic.dysfunction = 0, 
         effect_loop_left.ventricular.systolic.dysfunction = 0, effect_ccb_left.ventricular.systolic.dysfunction = 0, 
         effect_thiazide_left.ventricular.systolic.dysfunction = 0, 
         effect_sasid_left.ventricular.systolic.dysfunction = 0, effect_statin_left.ventricular.systolic.dysfunction = 0, 
         effect_hypertension_left.ventricular.systolic.dysfunction = 0, 
         effect_diabetic.nephropathy_left.ventricular.systolic.dysfunction = 0, 
         effect_stenosis_left.ventricular.systolic.dysfunction = 0, 
         effect_disorders.of.rhythm.or.conduction_left.ventricular.systolic.dysfunction = 0, 
         effect_gallstone.disease_left.ventricular.systolic.dysfunction = 0, 
         effect_pancreatitis_left.ventricular.systolic.dysfunction = 0, 
         effect_diabetic.foot.ulcer_left.ventricular.systolic.dysfunction = 0, 
         effect_diabetic.neuropathy_left.ventricular.systolic.dysfunction = 0, 
         effect_transient.ischaemic.attack_left.ventricular.systolic.dysfunction = 0, 
         effect_sex_gallstone.disease = 0, effect_age_gallstone.disease = 0, 
         effect_diabetesduration_gallstone.disease = 0, effect_egfr_gallstone.disease = 0, 
         effect_bmi_gallstone.disease = 0, effect_mineralcor_gallstone.disease = 0, 
         effect_bb_gallstone.disease = 0, effect_rasi_gallstone.disease = 0, 
         effect_loop_gallstone.disease = 0, effect_ccb_gallstone.disease = 0, 
         effect_thiazide_gallstone.disease = 0, effect_sasid_gallstone.disease = 0, 
         effect_statin_gallstone.disease = 0, effect_hypertension_gallstone.disease = 0, 
         effect_diabetic.nephropathy_gallstone.disease = 0, effect_stenosis_gallstone.disease = 0, 
         effect_disorders.of.rhythm.or.conduction_gallstone.disease = 0, 
         effect_left.ventricular.systolic.dysfunction_gallstone.disease = 0, 
         effect_pancreatitis_gallstone.disease = 0, effect_diabetic.foot.ulcer_gallstone.disease = 0, 
         effect_diabetic.neuropathy_gallstone.disease = 0, effect_transient.ischaemic.attack_gallstone.disease = 0, 
         effect_sex_pancreatitis = 0, effect_age_pancreatitis = 0, 
         effect_diabetesduration_pancreatitis = 0, effect_egfr_pancreatitis = 0, 
         effect_bmi_pancreatitis = 0, effect_mineralcor_pancreatitis = 0, 
         effect_bb_pancreatitis = 0, effect_rasi_pancreatitis = 0, 
         effect_loop_pancreatitis = 0, effect_ccb_pancreatitis = 0, 
         effect_thiazide_pancreatitis = 0, effect_sasid_pancreatitis = 0, 
         effect_statin_pancreatitis = 0, effect_hypertension_pancreatitis = 0, 
         effect_diabetic.nephropathy_pancreatitis = 0, effect_stenosis_pancreatitis = 0, 
         effect_disorders.of.rhythm.or.conduction_pancreatitis = 0, 
         effect_left.ventricular.systolic.dysfunction_pancreatitis = 0, 
         effect_gallstone.disease_pancreatitis = 0, effect_diabetic.foot.ulcer_pancreatitis = 0, 
         effect_diabetic.neuropathy_pancreatitis = 0, effect_transient.ischaemic.attack_pancreatitis = 0, 
         effect_sex_diabetic.foot.ulcer = 0, effect_age_diabetic.foot.ulcer = 0, 
         effect_diabetesduration_diabetic.foot.ulcer = 0, effect_egfr_diabetic.foot.ulcer = 0, 
         effect_bmi_diabetic.foot.ulcer = 0, effect_mineralcor_diabetic.foot.ulcer = 0, 
         effect_bb_diabetic.foot.ulcer = 0, effect_rasi_diabetic.foot.ulcer = 0, 
         effect_loop_diabetic.foot.ulcer = 0, effect_ccb_diabetic.foot.ulcer = 0, 
         effect_thiazide_diabetic.foot.ulcer = 0, effect_sasid_diabetic.foot.ulcer = 0, 
         effect_statin_diabetic.foot.ulcer = 0, effect_hypertension_diabetic.foot.ulcer = 0, 
         effect_diabetic.nephropathy_diabetic.foot.ulcer = 0, effect_stenosis_diabetic.foot.ulcer = 0, 
         effect_disorders.of.rhythm.or.conduction_diabetic.foot.ulcer = 0, 
         effect_left.ventricular.systolic.dysfunction_diabetic.foot.ulcer = 0, 
         effect_gallstone.disease_diabetic.foot.ulcer = 0, effect_pancreatitis_diabetic.foot.ulcer = 0, 
         effect_diabetic.neuropathy_diabetic.foot.ulcer = 0, effect_transient.ischaemic.attack_diabetic.foot.ulcer = 0, 
         effect_sex_diabetic.neuropathy = 0, effect_age_diabetic.neuropathy = 0, 
         effect_diabetesduration_diabetic.neuropathy = 0, effect_egfr_diabetic.neuropathy = 0, 
         effect_bmi_diabetic.neuropathy = 0, effect_mineralcor_diabetic.neuropathy = 0, 
         effect_bb_diabetic.neuropathy = 0, effect_rasi_diabetic.neuropathy = 0, 
         effect_loop_diabetic.neuropathy = 0, effect_ccb_diabetic.neuropathy = 0, 
         effect_thiazide_diabetic.neuropathy = 0, effect_sasid_diabetic.neuropathy = 0, 
         effect_statin_diabetic.neuropathy = 0, effect_hypertension_diabetic.neuropathy = 0, 
         effect_diabetic.nephropathy_diabetic.neuropathy = 0, effect_stenosis_diabetic.neuropathy = 0, 
         effect_disorders.of.rhythm.or.conduction_diabetic.neuropathy = 0, 
         effect_left.ventricular.systolic.dysfunction_diabetic.neuropathy = 0, 
         effect_gallstone.disease_diabetic.neuropathy = 0, effect_pancreatitis_diabetic.neuropathy = 0, 
         effect_diabetic.foot.ulcer_diabetic.neuropathy = 0, effect_transient.ischaemic.attack_diabetic.neuropathy = 0, 
         effect_sex_transient.ischaemic.attack = 0, effect_age_transient.ischaemic.attack = 0, 
         effect_diabetesduration_transient.ischaemic.attack = 0, effect_egfr_transient.ischaemic.attack = 0, 
         effect_bmi_transient.ischaemic.attack = 0, effect_mineralcor_transient.ischaemic.attack = 0, 
         effect_bb_transient.ischaemic.attack = 0, effect_rasi_transient.ischaemic.attack = 0, 
         effect_loop_transient.ischaemic.attack = 0, effect_ccb_transient.ischaemic.attack = 0, 
         effect_thiazide_transient.ischaemic.attack = 0, effect_sasid_transient.ischaemic.attack = 0, 
         effect_statin_transient.ischaemic.attack = 0, effect_hypertension_transient.ischaemic.attack = 0, 
         effect_diabetic.nephropathy_transient.ischaemic.attack = 0, 
         effect_stenosis_transient.ischaemic.attack = 0, effect_disorders.of.rhythm.or.conduction_transient.ischaemic.attack = 0, 
         effect_left.ventricular.systolic.dysfunction_transient.ischaemic.attack = 0, 
         effect_gallstone.disease_transient.ischaemic.attack = 0, 
         effect_pancreatitis_transient.ischaemic.attack = 0, effect_diabetic.foot.ulcer_transient.ischaemic.attack = 0, 
         effect_diabetic.neuropathy_transient.ischaemic.attack = 0, 
         effect_sex_start_GLP1RA = 0, effect_age_start_GLP1RA = 0, 
         effect_diabetesduration_start_GLP1RA = 0, effect_egfr_start_GLP1RA = 0, 
         effect_bmi_start_GLP1RA = 0, effect_mineralcor_start_GLP1RA = 0, 
         effect_bb_start_GLP1RA = 0, effect_rasi_start_GLP1RA = 0, 
         effect_loop_start_GLP1RA = 0, effect_ccb_start_GLP1RA = 0, 
         effect_thiazide_start_GLP1RA = 0, effect_sasid_start_GLP1RA = 0, 
         effect_statin_start_GLP1RA = 0, effect_hypertension_start_GLP1RA = 0, 
         effect_diabetic.nephropathy_start_GLP1RA = 0, effect_stenosis_start_GLP1RA = 0, 
         effect_disorders.of.rhythm.or.conduction_start_GLP1RA = 0, 
         effect_left.ventricular.systolic.dysfunction_start_GLP1RA = 0, 
         effect_gallstone.disease_start_GLP1RA = 0, effect_pancreatitis_start_GLP1RA = 0, 
         effect_diabetic.foot.ulcer_start_GLP1RA = 0, effect_diabetic.neuropathy_start_GLP1RA = 0, 
         effect_transient.ischaemic.attack_start_GLP1RA = 0, effect_sex_start_SGLT2i = 0, 
         effect_age_start_SGLT2i = 0, effect_diabetesduration_start_SGLT2i = 0, 
         effect_egfr_start_SGLT2i = 0, effect_bmi_start_SGLT2i = 0, 
         effect_mineralcor_start_SGLT2i = 0, effect_bb_start_SGLT2i = 0, 
         effect_rasi_start_SGLT2i = 0, effect_loop_start_SGLT2i = 0, 
         effect_ccb_start_SGLT2i = 0, effect_thiazide_start_SGLT2i = 0, 
         effect_sasid_start_SGLT2i = 0, effect_statin_start_SGLT2i = 0, 
         effect_hypertension_start_SGLT2i = 0, effect_diabetic.nephropathy_start_SGLT2i = 0, 
         effect_stenosis_start_SGLT2i = 0, effect_disorders.of.rhythm.or.conduction_start_SGLT2i = 0, 
         effect_left.ventricular.systolic.dysfunction_start_SGLT2i = 0, 
         effect_gallstone.disease_start_SGLT2i = 0, effect_pancreatitis_start_SGLT2i = 0, 
         effect_diabetic.foot.ulcer_start_SGLT2i = 0, effect_diabetic.neuropathy_start_SGLT2i = 0, 
         effect_transient.ischaemic.attack_start_SGLT2i = 0, effect_sex_metformin = 0, 
         effect_age_metformin = 0, effect_diabetesduration_metformin = 0, 
         effect_egfr_metformin = 0, effect_bmi_metformin = 0, effect_mineralcor_metformin = 0, 
         effect_bb_metformin = 0, effect_rasi_metformin = 0, effect_loop_metformin = 0, 
         effect_ccb_metformin = 0, effect_thiazide_metformin = 0, 
         effect_sasid_metformin = 0, effect_statin_metformin = 0, 
         effect_hypertension_metformin = 0, effect_diabetic.nephropathy_metformin = 0, 
         effect_stenosis_metformin = 0, effect_disorders.of.rhythm.or.conduction_metformin = 0, 
         effect_left.ventricular.systolic.dysfunction_metformin = 0, 
         effect_gallstone.disease_metformin = 0, effect_pancreatitis_metformin = 0, 
         effect_diabetic.foot.ulcer_metformin = 0, effect_diabetic.neuropathy_metformin = 0, 
         effect_transient.ischaemic.attack_metformin = 0, effect_sex_sulfonylurea = 0, 
         effect_age_sulfonylurea = 0, effect_diabetesduration_sulfonylurea = 0, 
         effect_egfr_sulfonylurea = 0, effect_bmi_sulfonylurea = 0, 
         effect_mineralcor_sulfonylurea = 0, effect_bb_sulfonylurea = 0, 
         effect_rasi_sulfonylurea = 0, effect_loop_sulfonylurea = 0, 
         effect_ccb_sulfonylurea = 0, effect_thiazide_sulfonylurea = 0, 
         effect_sasid_sulfonylurea = 0, effect_statin_sulfonylurea = 0, 
         effect_hypertension_sulfonylurea = 0, effect_diabetic.nephropathy_sulfonylurea = 0, 
         effect_stenosis_sulfonylurea = 0, effect_disorders.of.rhythm.or.conduction_sulfonylurea = 0, 
         effect_left.ventricular.systolic.dysfunction_sulfonylurea = 0, 
         effect_gallstone.disease_sulfonylurea = 0, effect_pancreatitis_sulfonylurea = 0, 
         effect_diabetic.foot.ulcer_sulfonylurea = 0, effect_diabetic.neuropathy_sulfonylurea = 0, 
         effect_transient.ischaemic.attack_sulfonylurea = 0, effect_sex_insulin = 0, 
         effect_age_insulin = 0, effect_diabetesduration_insulin = 0, 
         effect_egfr_insulin = 0, effect_bmi_insulin = 0, effect_mineralcor_insulin = 0, 
         effect_bb_insulin = 0, effect_rasi_insulin = 0, effect_loop_insulin = 0, 
         effect_ccb_insulin = 0, effect_thiazide_insulin = 0, effect_sasid_insulin = 0, 
         effect_statin_insulin = 0, effect_hypertension_insulin = 0, 
         effect_diabetic.nephropathy_insulin = 0, effect_stenosis_insulin = 0, 
         effect_disorders.of.rhythm.or.conduction_insulin = 0, effect_left.ventricular.systolic.dysfunction_insulin = 0, 
         effect_gallstone.disease_insulin = 0, effect_pancreatitis_insulin = 0, 
         effect_diabetic.foot.ulcer_insulin = 0, effect_diabetic.neuropathy_insulin = 0, 
         effect_transient.ischaemic.attack_insulin = 0, effect_sex_alfa_g_inhib = 0, 
         effect_age_alfa_g_inhib = 0, effect_diabetesduration_alfa_g_inhib = 0, 
         effect_egfr_alfa_g_inhib = 0, effect_bmi_alfa_g_inhib = 0, 
         effect_mineralcor_alfa_g_inhib = 0, effect_bb_alfa_g_inhib = 0, 
         effect_rasi_alfa_g_inhib = 0, effect_loop_alfa_g_inhib = 0, 
         effect_ccb_alfa_g_inhib = 0, effect_thiazide_alfa_g_inhib = 0, 
         effect_sasid_alfa_g_inhib = 0, effect_statin_alfa_g_inhib = 0, 
         effect_hypertension_alfa_g_inhib = 0, effect_diabetic.nephropathy_alfa_g_inhib = 0, 
         effect_stenosis_alfa_g_inhib = 0, effect_disorders.of.rhythm.or.conduction_alfa_g_inhib = 0, 
         effect_left.ventricular.systolic.dysfunction_alfa_g_inhib = 0, 
         effect_gallstone.disease_alfa_g_inhib = 0, effect_pancreatitis_alfa_g_inhib = 0, 
         effect_diabetic.foot.ulcer_alfa_g_inhib = 0, effect_diabetic.neuropathy_alfa_g_inhib = 0, 
         effect_transient.ischaemic.attack_alfa_g_inhib = 0, effect_sex_thiazo = 0, 
         effect_age_thiazo = 0, effect_diabetesduration_thiazo = 0, 
         effect_egfr_thiazo = 0, effect_bmi_thiazo = 0, effect_mineralcor_thiazo = 0, 
         effect_bb_thiazo = 0, effect_rasi_thiazo = 0, effect_loop_thiazo = 0, 
         effect_ccb_thiazo = 0, effect_thiazide_thiazo = 0, effect_sasid_thiazo = 0, 
         effect_statin_thiazo = 0, effect_hypertension_thiazo = 0, 
         effect_diabetic.nephropathy_thiazo = 0, effect_stenosis_thiazo = 0, 
         effect_disorders.of.rhythm.or.conduction_thiazo = 0, effect_left.ventricular.systolic.dysfunction_thiazo = 0, 
         effect_gallstone.disease_thiazo = 0, effect_pancreatitis_thiazo = 0, 
         effect_diabetic.foot.ulcer_thiazo = 0, effect_diabetic.neuropathy_thiazo = 0, 
         effect_transient.ischaemic.attack_thiazo = 0, effect_sex_insulin_one = 0, 
         effect_age_insulin_one = 0, effect_diabetesduration_insulin_one = 0, 
         effect_egfr_insulin_one = 0, effect_bmi_insulin_one = 0, 
         effect_mineralcor_insulin_one = 0, effect_bb_insulin_one = 0, 
         effect_rasi_insulin_one = 0, effect_loop_insulin_one = 0, 
         effect_ccb_insulin_one = 0, effect_thiazide_insulin_one = 0, 
         effect_sasid_insulin_one = 0, effect_statin_insulin_one = 0, 
         effect_hypertension_insulin_one = 0, effect_diabetic.nephropathy_insulin_one = 0, 
         effect_stenosis_insulin_one = 0, effect_disorders.of.rhythm.or.conduction_insulin_one = 0, 
         effect_left.ventricular.systolic.dysfunction_insulin_one = 0, 
         effect_gallstone.disease_insulin_one = 0, effect_pancreatitis_insulin_one = 0, 
         effect_diabetic.foot.ulcer_insulin_one = 0, effect_diabetic.neuropathy_insulin_one = 0, 
         effect_transient.ischaemic.attack_insulin_one = 0, effect_sex_dpp4 = 0, 
         effect_age_dpp4 = 0, effect_diabetesduration_dpp4 = 0, effect_egfr_dpp4 = 0, 
         effect_bmi_dpp4 = 0, effect_mineralcor_dpp4 = 0, effect_bb_dpp4 = 0, 
         effect_rasi_dpp4 = 0, effect_loop_dpp4 = 0, effect_ccb_dpp4 = 0, 
         effect_thiazide_dpp4 = 0, effect_sasid_dpp4 = 0, effect_statin_dpp4 = 0, 
         effect_hypertension_dpp4 = 0, effect_diabetic.nephropathy_dpp4 = 0, 
         effect_stenosis_dpp4 = 0, effect_disorders.of.rhythm.or.conduction_dpp4 = 0, 
         effect_left.ventricular.systolic.dysfunction_dpp4 = 0, effect_gallstone.disease_dpp4 = 0, 
         effect_pancreatitis_dpp4 = 0, effect_diabetic.foot.ulcer_dpp4 = 0, 
         effect_diabetic.neuropathy_dpp4 = 0, effect_transient.ischaemic.attack_dpp4 = 0, 
         effect_sex_hba1c_level = 0, effect_age_hba1c_level = 0, effect_diabetesduration_hba1c_level = 0, 
         effect_egfr_hba1c_level = 0, effect_bmi_hba1c_level = 0, 
         effect_mineralcor_hba1c_level = 0, effect_bb_hba1c_level = 0, 
         effect_rasi_hba1c_level = 0, effect_loop_hba1c_level = 0, 
         effect_ccb_hba1c_level = 0, effect_thiazide_hba1c_level = 0, 
         effect_sasid_hba1c_level = 0, effect_statin_hba1c_level = 0, 
         effect_hypertension_hba1c_level = 0, effect_diabetic.nephropathy_hba1c_level = 0, 
         effect_stenosis_hba1c_level = 0, effect_disorders.of.rhythm.or.conduction_hba1c_level = 0, 
         effect_left.ventricular.systolic.dysfunction_hba1c_level = 0, 
         effect_gallstone.disease_hba1c_level = 0, effect_pancreatitis_hba1c_level = 0, 
         effect_diabetic.foot.ulcer_hba1c_level = 0, effect_diabetic.neuropathy_hba1c_level = 0, 
         effect_transient.ischaemic.attack_hba1c_level = 0, effect_sex_hba1c_change = 0, 
         effect_age_hba1c_change = 0, effect_diabetesduration_hba1c_change = 0, 
         effect_egfr_hba1c_change = 0, effect_bmi_hba1c_change = 0, 
         effect_mineralcor_hba1c_change = 0, effect_bb_hba1c_change = 0, 
         effect_rasi_hba1c_change = 0, effect_loop_hba1c_change = 0, 
         effect_ccb_hba1c_change = 0, effect_thiazide_hba1c_change = 0, 
         effect_sasid_hba1c_change = 0, effect_statin_hba1c_change = 0, 
         effect_hypertension_hba1c_change = 0, effect_diabetic.nephropathy_hba1c_change = 0, 
         effect_stenosis_hba1c_change = 0, effect_disorders.of.rhythm.or.conduction_hba1c_change = 0, 
         effect_left.ventricular.systolic.dysfunction_hba1c_change = 0, 
         effect_gallstone.disease_hba1c_change = 0, effect_pancreatitis_hba1c_change = 0, 
         effect_diabetic.foot.ulcer_hba1c_change = 0, effect_diabetic.neuropathy_hba1c_change = 0, 
         effect_transient.ischaemic.attack_hba1c_change = 0, effect_sex_cv.death = 0, 
         effect_age_cv.death = 0, effect_diabetesduration_cv.death = 0, 
         effect_egfr_cv.death = 0, effect_bmi_cv.death = 0, effect_mineralcor_cv.death = 0, 
         effect_bb_cv.death = 0, effect_rasi_cv.death = 0, effect_loop_cv.death = 0, 
         effect_ccb_cv.death = 0, effect_thiazide_cv.death = 0, effect_sasid_cv.death = 0, 
         effect_statin_cv.death = 0, effect_hypertension_cv.death = 0, 
         effect_diabetic.nephropathy_cv.death = 0, effect_stenosis_cv.death = 0, 
         effect_disorders.of.rhythm.or.conduction_cv.death = 0, effect_left.ventricular.systolic.dysfunction_cv.death = 0, 
         effect_gallstone.disease_cv.death = 0, effect_pancreatitis_cv.death = 0, 
         effect_diabetic.foot.ulcer_cv.death = 0, effect_diabetic.neuropathy_cv.death = 0, 
         effect_transient.ischaemic.attack_cv.death = 0, effect_sex_all.cause.mortality = 0, 
         effect_age_all.cause.mortality = 0, effect_diabetesduration_all.cause.mortality = 0, 
         effect_egfr_all.cause.mortality = 0, effect_bmi_all.cause.mortality = 0, 
         effect_mineralcor_all.cause.mortality = 0, effect_bb_all.cause.mortality = 0, 
         effect_rasi_all.cause.mortality = 0, effect_loop_all.cause.mortality = 0, 
         effect_ccb_all.cause.mortality = 0, effect_thiazide_all.cause.mortality = 0, 
         effect_sasid_all.cause.mortality = 0, effect_statin_all.cause.mortality = 0, 
         effect_hypertension_all.cause.mortality = 0, effect_diabetic.nephropathy_all.cause.mortality = 0, 
         effect_stenosis_all.cause.mortality = 0, effect_disorders.of.rhythm.or.conduction_all.cause.mortality = 0, 
         effect_left.ventricular.systolic.dysfunction_all.cause.mortality = 0, 
         effect_gallstone.disease_all.cause.mortality = 0, effect_pancreatitis_all.cause.mortality = 0, 
         effect_diabetic.foot.ulcer_all.cause.mortality = 0, effect_diabetic.neuropathy_all.cause.mortality = 0, 
         effect_transient.ischaemic.attack_all.cause.mortality = 0, 
         effect_sex_dropout = 0, effect_age_dropout = 0, effect_diabetesduration_dropout = 0, 
         effect_egfr_dropout = 0, effect_bmi_dropout = 0, effect_mineralcor_dropout = 0, 
         effect_bb_dropout = 0, effect_rasi_dropout = 0, effect_loop_dropout = 0, 
         effect_ccb_dropout = 0, effect_thiazide_dropout = 0, effect_sasid_dropout = 0, 
         effect_statin_dropout = 0, effect_hypertension_dropout = 0, 
         effect_diabetic.nephropathy_dropout = 0, effect_stenosis_dropout = 0, 
         effect_disorders.of.rhythm.or.conduction_dropout = 0, effect_left.ventricular.systolic.dysfunction_dropout = 0, 
         effect_gallstone.disease_dropout = 0, effect_pancreatitis_dropout = 0, 
         effect_diabetic.foot.ulcer_dropout = 0, effect_diabetic.neuropathy_dropout = 0, 
         effect_transient.ischaemic.attack_dropout = 0, effect_sex_mi = 0, 
         effect_age_mi = 0, effect_diabetesduration_mi = 0, effect_egfr_mi = 0, 
         effect_bmi_mi = 0, effect_mineralcor_mi = 0, effect_bb_mi = 0, 
         effect_rasi_mi = 0, effect_loop_mi = 0, effect_ccb_mi = 0, 
         effect_thiazide_mi = 0, effect_sasid_mi = 0, effect_statin_mi = 0, 
         effect_hypertension_mi = 0, effect_diabetic.nephropathy_mi = 0, 
         effect_stenosis_mi = 0, effect_disorders.of.rhythm.or.conduction_mi = 0, 
         effect_left.ventricular.systolic.dysfunction_mi = 0, effect_gallstone.disease_mi = 0, 
         effect_pancreatitis_mi = 0, effect_diabetic.foot.ulcer_mi = 0, 
         effect_diabetic.neuropathy_mi = 0, effect_transient.ischaemic.attack_mi = 0, 
         effect_sex_stroke = 0, effect_age_stroke = 0, effect_diabetesduration_stroke = 0, 
         effect_egfr_stroke = 0, effect_bmi_stroke = 0, effect_mineralcor_stroke = 0, 
         effect_bb_stroke = 0, effect_rasi_stroke = 0, effect_loop_stroke = 0, 
         effect_ccb_stroke = 0, effect_thiazide_stroke = 0, effect_sasid_stroke = 0, 
         effect_statin_stroke = 0, effect_hypertension_stroke = 0, 
         effect_diabetic.nephropathy_stroke = 0, effect_stenosis_stroke = 0, 
         effect_disorders.of.rhythm.or.conduction_stroke = 0, effect_left.ventricular.systolic.dysfunction_stroke = 0, 
         effect_gallstone.disease_stroke = 0, effect_pancreatitis_stroke = 0, 
         effect_diabetic.foot.ulcer_stroke = 0, effect_diabetic.neuropathy_stroke = 0, 
         effect_transient.ischaemic.attack_stroke = 0, effect_sex_uap = 0, 
         effect_age_uap = 0, effect_diabetesduration_uap = 0, effect_egfr_uap = 0, 
         effect_bmi_uap = 0, effect_mineralcor_uap = 0, effect_bb_uap = 0, 
         effect_rasi_uap = 0, effect_loop_uap = 0, effect_ccb_uap = 0, 
         effect_thiazide_uap = 0, effect_sasid_uap = 0, effect_statin_uap = 0, 
         effect_hypertension_uap = 0, effect_diabetic.nephropathy_uap = 0, 
         effect_stenosis_uap = 0, effect_disorders.of.rhythm.or.conduction_uap = 0, 
         effect_left.ventricular.systolic.dysfunction_uap = 0, effect_gallstone.disease_uap = 0, 
         effect_pancreatitis_uap = 0, effect_diabetic.foot.ulcer_uap = 0, 
         effect_diabetic.neuropathy_uap = 0, effect_transient.ischaemic.attack_uap = 0, 
         effect_sex_revasc = 0, effect_age_revasc = 0, effect_diabetesduration_revasc = 0, 
         effect_egfr_revasc = 0, effect_bmi_revasc = 0, effect_mineralcor_revasc = 0, 
         effect_bb_revasc = 0, effect_rasi_revasc = 0, effect_loop_revasc = 0, 
         effect_ccb_revasc = 0, effect_thiazide_revasc = 0, effect_sasid_revasc = 0, 
         effect_statin_revasc = 0, effect_hypertension_revasc = 0, 
         effect_diabetic.nephropathy_revasc = 0, effect_stenosis_revasc = 0, 
         effect_disorders.of.rhythm.or.conduction_revasc = 0, effect_left.ventricular.systolic.dysfunction_revasc = 0, 
         effect_gallstone.disease_revasc = 0, effect_pancreatitis_revasc = 0, 
         effect_diabetic.foot.ulcer_revasc = 0, effect_diabetic.neuropathy_revasc = 0, 
         effect_transient.ischaemic.attack_revasc = 0, effect_sex_heart.failure = 0, 
         effect_age_heart.failure = 0, effect_diabetesduration_heart.failure = 0, 
         effect_egfr_heart.failure = 0, effect_bmi_heart.failure = 0, 
         effect_mineralcor_heart.failure = 0, effect_bb_heart.failure = 0, 
         effect_rasi_heart.failure = 0, effect_loop_heart.failure = 0, 
         effect_ccb_heart.failure = 0, effect_thiazide_heart.failure = 0, 
         effect_sasid_heart.failure = 0, effect_statin_heart.failure = 0, 
         effect_hypertension_heart.failure = 0, effect_diabetic.nephropathy_heart.failure = 0, 
         effect_stenosis_heart.failure = 0, effect_disorders.of.rhythm.or.conduction_heart.failure = 0, 
         effect_left.ventricular.systolic.dysfunction_heart.failure = 0, 
         effect_gallstone.disease_heart.failure = 0, effect_pancreatitis_heart.failure = 0, 
         effect_diabetic.foot.ulcer_heart.failure = 0, effect_diabetic.neuropathy_heart.failure = 0, 
         effect_transient.ischaemic.attack_heart.failure = 0, effect_sex_atrial.fibrillation = 0, 
         effect_age_atrial.fibrillation = 0, effect_diabetesduration_atrial.fibrillation = 0, 
         effect_egfr_atrial.fibrillation = 0, effect_bmi_atrial.fibrillation = 0, 
         effect_mineralcor_atrial.fibrillation = 0, effect_bb_atrial.fibrillation = 0, 
         effect_rasi_atrial.fibrillation = 0, effect_loop_atrial.fibrillation = 0, 
         effect_ccb_atrial.fibrillation = 0, effect_thiazide_atrial.fibrillation = 0, 
         effect_sasid_atrial.fibrillation = 0, effect_statin_atrial.fibrillation = 0, 
         effect_hypertension_atrial.fibrillation = 0, effect_diabetic.nephropathy_atrial.fibrillation = 0, 
         effect_stenosis_atrial.fibrillation = 0, effect_disorders.of.rhythm.or.conduction_atrial.fibrillation = 0, 
         effect_left.ventricular.systolic.dysfunction_atrial.fibrillation = 0, 
         effect_gallstone.disease_atrial.fibrillation = 0, effect_pancreatitis_atrial.fibrillation = 0, 
         effect_diabetic.foot.ulcer_atrial.fibrillation = 0, effect_diabetic.neuropathy_atrial.fibrillation = 0, 
         effect_transient.ischaemic.attack_atrial.fibrillation = 0, 
         effect_sex_nausea.and.vomiting.symptoms = 0, effect_age_nausea.and.vomiting.symptoms = 0, 
         effect_diabetesduration_nausea.and.vomiting.symptoms = 0, 
         effect_egfr_nausea.and.vomiting.symptoms = 0, effect_bmi_nausea.and.vomiting.symptoms = 0, 
         effect_mineralcor_nausea.and.vomiting.symptoms = 0, effect_bb_nausea.and.vomiting.symptoms = 0, 
         effect_rasi_nausea.and.vomiting.symptoms = 0, effect_loop_nausea.and.vomiting.symptoms = 0, 
         effect_ccb_nausea.and.vomiting.symptoms = 0, effect_thiazide_nausea.and.vomiting.symptoms = 0, 
         effect_sasid_nausea.and.vomiting.symptoms = 0, effect_statin_nausea.and.vomiting.symptoms = 0, 
         effect_hypertension_nausea.and.vomiting.symptoms = 0, effect_diabetic.nephropathy_nausea.and.vomiting.symptoms = 0, 
         effect_stenosis_nausea.and.vomiting.symptoms = 0, effect_disorders.of.rhythm.or.conduction_nausea.and.vomiting.symptoms = 0, 
         effect_left.ventricular.systolic.dysfunction_nausea.and.vomiting.symptoms = 0, 
         effect_gallstone.disease_nausea.and.vomiting.symptoms = 0, 
         effect_pancreatitis_nausea.and.vomiting.symptoms = 0, effect_diabetic.foot.ulcer_nausea.and.vomiting.symptoms = 0, 
         effect_diabetic.neuropathy_nausea.and.vomiting.symptoms = 0, 
         effect_transient.ischaemic.attack_nausea.and.vomiting.symptoms = 0, 
         effect_sex_diarrhoea = 0, effect_age_diarrhoea = 0, effect_diabetesduration_diarrhoea = 0, 
         effect_egfr_diarrhoea = 0, effect_bmi_diarrhoea = 0, effect_mineralcor_diarrhoea = 0, 
         effect_bb_diarrhoea = 0, effect_rasi_diarrhoea = 0, effect_loop_diarrhoea = 0, 
         effect_ccb_diarrhoea = 0, effect_thiazide_diarrhoea = 0, 
         effect_sasid_diarrhoea = 0, effect_statin_diarrhoea = 0, 
         effect_hypertension_diarrhoea = 0, effect_diabetic.nephropathy_diarrhoea = 0, 
         effect_stenosis_diarrhoea = 0, effect_disorders.of.rhythm.or.conduction_diarrhoea = 0, 
         effect_left.ventricular.systolic.dysfunction_diarrhoea = 0, 
         effect_gallstone.disease_diarrhoea = 0, effect_pancreatitis_diarrhoea = 0, 
         effect_diabetic.foot.ulcer_diarrhoea = 0, effect_diabetic.neuropathy_diarrhoea = 0, 
         effect_transient.ischaemic.attack_diarrhoea = 0, effect_mi_cv.death = 0, 
         effect_stroke_cv.death = 0, effect_uap_cv.death = 0, effect_revasc_cv.death = 0, 
         effect_heart.failure_cv.death = 0, effect_atrial.fibrillation_cv.death = 0, 
         effect_nausea.and.vomiting.symptoms_cv.death = 0, effect_diarrhoea_cv.death = 0, 
         effect_hba1c_level_cv.death = 0, effect_hba1c_change_cv.death = 0, 
         effect_metformin_cv.death = 0, effect_sulfonylurea_cv.death = 0, 
         effect_insulin_cv.death = 0, effect_alfa_g_inhib_cv.death = 0, 
         effect_thiazo_cv.death = 0, effect_insulin_one_cv.death = 0, 
         effect_dpp4_cv.death = 0, effect_mi_all.cause.mortality = 0, 
         effect_stroke_all.cause.mortality = 0, effect_uap_all.cause.mortality = 0, 
         effect_revasc_all.cause.mortality = 0, effect_heart.failure_all.cause.mortality = 0, 
         effect_atrial.fibrillation_all.cause.mortality = 0, effect_nausea.and.vomiting.symptoms_all.cause.mortality = 0, 
         effect_diarrhoea_all.cause.mortality = 0, effect_hba1c_level_all.cause.mortality = 0, 
         effect_hba1c_change_all.cause.mortality = 0, effect_metformin_all.cause.mortality = 0, 
         effect_sulfonylurea_all.cause.mortality = 0, effect_insulin_all.cause.mortality = 0, 
         effect_alfa_g_inhib_all.cause.mortality = 0, effect_thiazo_all.cause.mortality = 0, 
         effect_insulin_one_all.cause.mortality = 0, effect_dpp4_all.cause.mortality = 0, 
         effect_mi_dropout = 0, effect_stroke_dropout = 0, effect_uap_dropout = 0, 
         effect_revasc_dropout = 0, effect_heart.failure_dropout = 0, 
         effect_atrial.fibrillation_dropout = 0, effect_nausea.and.vomiting.symptoms_dropout = 0, 
         effect_diarrhoea_dropout = 0, effect_hba1c_level_dropout = 0, 
         effect_hba1c_change_dropout = 0, effect_metformin_dropout = 0, 
         effect_sulfonylurea_dropout = 0, effect_insulin_dropout = 0, 
         effect_alfa_g_inhib_dropout = 0, effect_thiazo_dropout = 0, 
         effect_insulin_one_dropout = 0, effect_dpp4_dropout = 0, 
         effect_stroke_mi = 0, effect_uap_mi = 0, effect_revasc_mi = 0, 
         effect_heart.failure_mi = 0, effect_atrial.fibrillation_mi = 0, 
         effect_nausea.and.vomiting.symptoms_mi = 0, effect_diarrhoea_mi = 0, 
         effect_hba1c_level_mi = 0, effect_hba1c_change_mi = 0, effect_metformin_mi = 0, 
         effect_sulfonylurea_mi = 0, effect_insulin_mi = 0, effect_alfa_g_inhib_mi = 0, 
         effect_thiazo_mi = 0, effect_insulin_one_mi = 0, effect_dpp4_mi = 0, 
         effect_mi_stroke = 0, effect_uap_stroke = 0, effect_revasc_stroke = 0, 
         effect_heart.failure_stroke = 0, effect_atrial.fibrillation_stroke = 0, 
         effect_nausea.and.vomiting.symptoms_stroke = 0, effect_diarrhoea_stroke = 0, 
         effect_hba1c_level_stroke = 0, effect_hba1c_change_stroke = 0, 
         effect_metformin_stroke = 0, effect_sulfonylurea_stroke = 0, 
         effect_insulin_stroke = 0, effect_alfa_g_inhib_stroke = 0, 
         effect_thiazo_stroke = 0, effect_insulin_one_stroke = 0, 
         effect_dpp4_stroke = 0, effect_mi_uap = 0, effect_stroke_uap = 0, 
         effect_revasc_uap = 0, effect_heart.failure_uap = 0, effect_atrial.fibrillation_uap = 0, 
         effect_nausea.and.vomiting.symptoms_uap = 0, effect_diarrhoea_uap = 0, 
         effect_hba1c_level_uap = 0, effect_hba1c_change_uap = 0, 
         effect_metformin_uap = 0, effect_sulfonylurea_uap = 0, effect_insulin_uap = 0, 
         effect_alfa_g_inhib_uap = 0, effect_thiazo_uap = 0, effect_insulin_one_uap = 0, 
         effect_dpp4_uap = 0, effect_mi_revasc = 0, effect_stroke_revasc = 0, 
         effect_uap_revasc = 0, effect_heart.failure_revasc = 0, effect_atrial.fibrillation_revasc = 0, 
         effect_nausea.and.vomiting.symptoms_revasc = 0, effect_diarrhoea_revasc = 0, 
         effect_hba1c_level_revasc = 0, effect_hba1c_change_revasc = 0, 
         effect_metformin_revasc = 0, effect_sulfonylurea_revasc = 0, 
         effect_insulin_revasc = 0, effect_alfa_g_inhib_revasc = 0, 
         effect_thiazo_revasc = 0, effect_insulin_one_revasc = 0, 
         effect_dpp4_revasc = 0, effect_mi_heart.failure = 0, effect_stroke_heart.failure = 0, 
         effect_uap_heart.failure = 0, effect_revasc_heart.failure = 0, 
         effect_atrial.fibrillation_heart.failure = 0, effect_nausea.and.vomiting.symptoms_heart.failure = 0, 
         effect_diarrhoea_heart.failure = 0, effect_hba1c_level_heart.failure = 0, 
         effect_hba1c_change_heart.failure = 0, effect_metformin_heart.failure = 0, 
         effect_sulfonylurea_heart.failure = 0, effect_insulin_heart.failure = 0, 
         effect_alfa_g_inhib_heart.failure = 0, effect_thiazo_heart.failure = 0, 
         effect_insulin_one_heart.failure = 0, effect_dpp4_heart.failure = 0, 
         effect_mi_atrial.fibrillation = 0, effect_stroke_atrial.fibrillation = 0, 
         effect_uap_atrial.fibrillation = 0, effect_revasc_atrial.fibrillation = 0, 
         effect_heart.failure_atrial.fibrillation = 0, effect_nausea.and.vomiting.symptoms_atrial.fibrillation = 0, 
         effect_diarrhoea_atrial.fibrillation = 0, effect_hba1c_level_atrial.fibrillation = 0, 
         effect_hba1c_change_atrial.fibrillation = 0, effect_metformin_atrial.fibrillation = 0, 
         effect_sulfonylurea_atrial.fibrillation = 0, effect_insulin_atrial.fibrillation = 0, 
         effect_alfa_g_inhib_atrial.fibrillation = 0, effect_thiazo_atrial.fibrillation = 0, 
         effect_insulin_one_atrial.fibrillation = 0, effect_dpp4_atrial.fibrillation = 0, 
         effect_mi_nausea.and.vomiting.symptoms = 0, effect_stroke_nausea.and.vomiting.symptoms = 0, 
         effect_uap_nausea.and.vomiting.symptoms = 0, effect_revasc_nausea.and.vomiting.symptoms = 0, 
         effect_heart.failure_nausea.and.vomiting.symptoms = 0, effect_atrial.fibrillation_nausea.and.vomiting.symptoms = 0, 
         effect_diarrhoea_nausea.and.vomiting.symptoms = 0, effect_hba1c_level_nausea.and.vomiting.symptoms = 0, 
         effect_hba1c_change_nausea.and.vomiting.symptoms = 0, effect_metformin_nausea.and.vomiting.symptoms = 0, 
         effect_sulfonylurea_nausea.and.vomiting.symptoms = 0, effect_insulin_nausea.and.vomiting.symptoms = 0, 
         effect_alfa_g_inhib_nausea.and.vomiting.symptoms = 0, effect_thiazo_nausea.and.vomiting.symptoms = 0, 
         effect_insulin_one_nausea.and.vomiting.symptoms = 0, effect_dpp4_nausea.and.vomiting.symptoms = 0, 
         effect_mi_diarrhoea = 0, effect_stroke_diarrhoea = 0, effect_uap_diarrhoea = 0, 
         effect_revasc_diarrhoea = 0, effect_heart.failure_diarrhoea = 0, 
         effect_atrial.fibrillation_diarrhoea = 0, effect_nausea.and.vomiting.symptoms_diarrhoea = 0, 
         effect_hba1c_level_diarrhoea = 0, effect_hba1c_change_diarrhoea = 0, 
         effect_metformin_diarrhoea = 0, effect_sulfonylurea_diarrhoea = 0, 
         effect_insulin_diarrhoea = 0, effect_alfa_g_inhib_diarrhoea = 0, 
         effect_thiazo_diarrhoea = 0, effect_insulin_one_diarrhoea = 0, 
         effect_dpp4_diarrhoea = 0)    

    # Randomized baseline treatment (NOT USED)
    randomize_baseline_treatment <- function(X){
        X[,GLP1RA := 1*(start_GLP1RA == 1)]
        X[,SGLT2i := 1*(start_SGLT2i == 1 & start_GLP1RA == 0)]
        X[,start_GLP1 := NULL]
        X[,start_SGLT2 := NULL]
        X[]
    }

    # Output
    list(
        max_follow = max_follow,
        baseline_variables = baseline_variables,
        baseline_visit = baseline_visit,
        absorbing_events = absorbing_events,
        intermediate_events = intermediate_events,
        visit_measurements = visit_measurements,
        visit_events = visit_events,
        visit_schedule = visit_schedule,
        parameter_values = ipv
    )
    
}

if (FALSE) {
    
    d <- do.call(
        simulate_cohort,
        c(
            list(
                n = 1000#,
                #post_baseline_visit_hook = randomize_baseline_treatment
            ),
            p
        )
    )
    
}









######################################################################
### get_LEADER_setting.R ends here
